spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phuongtien
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: always
      schema-locations: file:init_db.sql
      separator: ;
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /chia-se/api

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /custom-swagger.json
